language: swift
rvm: 2.0.0
os: osx
osx_image: xcode7.3

before_install:
  - gem install cocoapods
script:
  - xctool -workspace Genome.xcworkspace -scheme Genome -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - echo "Running xcodebuild instead of xctool temporarily to work around xctool bug"
  - xcodebuild test -workspace Genome.xcworkspace -scheme GenomeTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
